name: Build and Deploy to Cloud Run
 # masterブランチにプッシュされたタイミング
on:
  push:
    branches: [ master ]
# 環境変数
env:
  SERVICE_NAME: test-service
  REGION: asia-northeast1
# 実行する作業の定義
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # コードを取得するステップ
    - name: Checkout code
      uses: actions/checkout@v4

### ここから 新規追加ステップ部分 ###
    # GitHubでの仮想マシン(ランナー)のPythonセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 依存関係のインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    # テストを実行するステップ
    - name: Run tests
      run: |
        pytest
### ここまで 新規追加ステップ部分 ###

    # Google 認証のステップ
    - name: Authenticate to Google Cloud
      if: success()  # テストが成功した場合のみ実行
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # SDKによるコマンドを利用できるようにするステップ
    - name: Set up Cloud SDK
      if: success()  # テストが成功した場合のみ実行
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # デバッグ認証ステップ
    - name: Debug Authentication
      if: success()  # テストが成功した場合のみ実行
      run: |
        echo "Current project: $(gcloud config get-value project)"
        echo "Current account: $(gcloud auth list --filter=status:ACTIVE --format='value(account)')"

    # Cloud Runにデプロイ (テストが成功した場合のみ)
    - name: Deploy to Cloud Run
      if: success()  # テストが成功した場合のみ実行
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --source . \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated
